scaleway/scaleway-cloud-controller-manager

.github/workflows/merge.yaml, .github/workflows/release.yml, Dockerfile, Makefile
=> fix: set right version in ccm on master

scaleway/sync.go, scaleway/sync_test.go
=> feat: add syncing taints from labels

Dockerfile
=> fix: add ca certificates

Dockerfile
=> fix: dockerfile base alpine

scaleway/sync.go
=> feat: add sync queue

scaleway/sync.go
=> fix: do not add taints to labels

docs/loadbalancer-annotations.md, scaleway/loadbalancers.go
=> feat(docs): fix the annotations docs

scaleway/instances.go, scaleway/instances_test.go
=> feat: use new dns names for instances

scaleway/sync.go
=> feat: add ServiceNodeExclusion label handling

README.md, docs/tags.md
=> doc: docuement release branches and tags management

Dockerfile, Makefile, scaleway/cloud.go, scaleway/version.go
=> feat: add EXTRA_USER_AGENT env

Dockerfile, Makefile, scaleway/cloud.go, scaleway/version.go
=> feat: add EXTRA_USER_AGENT env (#26)

.github/workflows/backport.yml
=> feat: add backport action

docs/loadbalancer-annotations.md, scaleway/loadbalancers.go
=> feat: add http protocol and certificate IDs for LB

.github/workflows/backport.yml
=> feat: use github app token

.github/workflows/backport.yml
=> feat: use scaleway bot token on backports

docs/loadbalancer-annotations.md, scaleway/loadbalancers.go
=> [Backport release-0.19] feat: add http protocol and certificate IDs for LB (#29)

docs/loadbalancer-annotations.md, scaleway/loadbalancers.go
=> [Backport release-0.18] feat: add http protocol and certificate IDs for LB (#29)

scaleway/baremetal.go, scaleway/instances.go, scaleway/loadbalancers.go, scaleway/utils.go
=> fix: handle all types of 404

scaleway/baremetal.go, scaleway/instances.go, scaleway/loadbalancers.go, scaleway/utils.go
=> Backport #37 into release-0.18: fix: handle all types of 404

scaleway/baremetal.go, scaleway/instances.go, scaleway/loadbalancers.go, scaleway/utils.go
=> Backport #37 into release-0.19: fix: handle all types of 404

scaleway/cloud.go, scaleway/loadbalancers.go
=> [Backport #35] feat: allow to disable interfaces and set default lb type (#35)

docs/tags.md, scaleway/sync.go, scaleway/sync_test.go
=> fix: allow prefixes in tags and taints with noprefix

scaleway/loadbalancers.go
=> fix(lb): remove region loop on get lb by name

scaleway/loadbalancers.go
=> fix(lb): remove region loop on get lb by name (backport #57)

scaleway/loadbalancers.go
=> feat(lb): add HTTPS health checks

scaleway/loadbalancers.go
=> feat(lb): add HTTPS health checks (#63)

scaleway/loadbalancers.go, scaleway/loadbalancers_test.go
=> feat(lb): add HC per port

examples/k8s-scaleway-secret.yml
Added an env variable for the zone which is required by the API
=> Field Zone cannot be empty in request

scaleway/baremetal.go, scaleway/instances.go
scw.AllZones contains zones that could not be available for those APIs
=> fix: list servers only in available zones

docs/loadbalancer-annotations.md, scaleway/loadbalancers.go
Add missing type 'first' for forward port algorithm.
=> feat(lb): add forward port algorithm 'first'

docs/loadbalancer-annotations.md, scaleway/loadbalancers.go, scaleway/loadbalancers_test.go
=> feat(lb): support host headers on http healthchecks

docs/loadbalancer-annotations.md, docs/loadbalancer-examples.md, scaleway/loadbalancers.go, scaleway/loadbalancers_annotations.go, scaleway/loadbalancers_test.go
=> feat: add service.beta.kubernetes.io/scw-loadbalancer-ip-ids annotation
